# Let travis know the language it needs to run
language: python

# Mention the python version in which travis will run the app
python:
  - "3.6"


# command to install dependencies in the requirements file
# You can also install the coverage here to avoid it being in the requirements file
# It is important to avoid things like coverage, pep8 that are not required to run the app
install:
  - pip install -r requirements.txt
  

# command to run tests 
# This is the script that enables travis to run the tests
# There are many ways to do dependeing on how you want travis to run and get you coverage
script: true
  - nosetests --with-coverage --coverage report
  
 # Another command/method to run tests
script: 
  - python TestCalculator.py

deploy:
  provider: heroku
  api_key:
    secure: de226378-f4c5-48fb-ba75-6b8e4cb5805f
  app: lab4useheroku
  on:
    repo: f2212671555/lab4
  #Setting your heroku Procfile here!!!
  run:
    "web: gunicorn app_run:app"
